name: Generate scss vars from figma tokens

on:
  push:
    branches:
      - issue-995-design-tokens
    paths:
      - 'figma-tokens/input/**'

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuring Node.js Environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      # Setting dependencies
      - name: Install dependencies
        run: npm ci

      # Token conversion using token-transformer
      - name: Transform Figma tokens
        run: npx token-transformer figma-tokens/input/tokens.json figma-tokens/transformed-tokens/tokens-transformed.json

      # Run script for Style Dictionary, convert JSON to SCSS
      - name: Build Figma tokens to SCSS
        run: npm run build-tokens

      # Create or update the `update-figma-tokens` branch
      - name: Create or update branch
        run: |
          git fetch origin
          git add figma-tokens/transformed-tokens/tokens-transformed.json
          git add stories/assets/scss/figma-scss/_figma-variables.scss
          git commit -m "Save changes before switching branch"
          if git ls-remote --exit-code --heads origin update-figma-tokens; then
            git checkout update-figma-tokens
            git pull --rebase origin update-figma-tokens
          else
            git checkout -b update-figma-tokens
          fi
          git add stories/assets/scss/figma-scss/_figma-variables.scss
          git commit -m "build: update SCSS variables and tokens" || echo "No changes to commit"

      # Push changes to `update-figma-tokens` branch
      - name: Push changes
        run: |
          git push origin update-figma-tokens

      # Automatically add and commit all changes including SCSS
      - name: Auto commit updated tokens and SCSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: update SCSS variables and tokens"
          file_pattern: stories/assets/scss/figma-scss/_figma-variables.scss
          branch: update-figma-tokens # Commit to the new branch

      # Automatic pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-figma-tokens
          base: develop  # Target branch for the PR
          commit-message: "build: update SCSS variables from Figma tokens"
          title: "Update SCSS variables from Figma tokens"
          body: "This PR updates SCSS variables based on the latest Figma tokens."
